service: xkcdbot
frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
functions:
  receive:
    handler: handler.receive
    events:
      - http:
          path: receive
          method: post
plugins:
  - serverless-ruby-package
package:
  include:
    - handler.rb
